# Generated by Django 5.2.1 on 2025-05-13 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M3L5DZ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('data', models.CharField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M3L5DZ.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M3L5DZ.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('number', models.IntegerField()),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M3L5DZ.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M3L5DZ.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M3L5DZ.teacher')),
            ],
        ),
    ]
